export const disasters = [
  { type: "Tropical Cyclone", color: "RED" },
  { type: "Mud Slide", color: "BROWN" },
  { type: "Flash Flood", color: "DARKBLUE" },
  { type: "Wild Fire", color: "ORANGE" },
  { type: "Cold Wave", color: "CYAN" },
  { type: "Technological Disaster", color: "GRAY" },
  { type: "Snow Avalanche", color: "LIGHTSKYBLUE" },
  { type: "Volcano", color: "DARKRED" },
  { type: "Fire", color: "FIREBRICK" },
  { type: "Epidemic", color: "GREENYELLOW" },
  { type: "Storm Surge", color: "STEELBLUE" },
  { type: "Tsunami", color: "DEEPSKYBLUE" },
  { type: "Insect Infestation", color: "OLIVE" },
  { type: "Drought", color: "TAN" },
  { type: "Earthquake", color: "SIENNA" },
  { type: "Flood", color: "NAVY" },
  { type: "Land Slide", color: "SADDLEBROWN" },
  { type: "Severe Local Storm", color: "DARKSLATEGRAY" },
  { type: "Extratropical Cyclone", color: "DARKORCHID" },
  { type: "Heat Wave", color: "RED" },
  { type: "Forest Fire", color: "ORANGE" },
  { type: "Other", color: "WHITE" },
];

export const getDefaultColor = () => "WHITE";
